### ISSUE TITLE
Documentation does not state jPBC library is required.

### ISSUE THREAD

**Issue by liusiyu1** [kisselz/redactable-sigs#5]
BUILD FAILED
/home/lsy/code/redactable-sigs-main/build.xml:22: Compile failed; see the compiler error output for details.

**Comment by kisselz** [comment]
The readme directions were incomplete. The ANT build script has been updated to automatically download the dependencies.

**Comment by liusiyu1** [comment]
> The readme directions were incomplete. The ANT build script has been updated to automatically download the dependencies.

BUILD SUCCESSFUL！Thanks！But where can I change the input（message） and see the output（sign）？

**Comment by liusiyu1** [comment]
> > The readme directions were incomplete. The ANT build script has been updated to automatically download the dependencies.
> 
> BUILD SUCCESSFUL！Thanks！But where can I change the input（message） and see the output（sign）？

What commands do I use?  ant -s？It‘s not true.

**Comment by liusiyu1** [comment]
BUILD SUCCESSFUL！Thanks！But what the java result mean? And how can I see the signature and the signature after redact? If I want to change the input, whether I modify Main.java(hello,world,dog,cat...)?

**Comment by liusiyu1** [comment]
BUILD SUCCESSFUL！Thanks！But what the java result:1 mean? And how can I see the signature and the signature after redact? If I want to change the input, whether I modify Main.java(hello,world,dog,cat...)?

**Comment by liusiyu1** [comment]
BUILD SUCCESSFUL！Thanks！
1. But what the java result:1 mean? 
2. And how can I see the signature and the signature after redact? 
3. If I want to change the input, whether I modify Main.java(hello,world,dog,cat...)?

**Comment by liusiyu1** [comment]
BUILD SUCCESSFUL！Thanks！
1. But what the java result:1 mean?
2. And how can I see the signature and the signature after redact?Use comments like ant -s and ant-r?
3. If I want to change the input, whether I modify ?Main.java(hello,world,dog,cat...)?

**Comment by liusiyu1** [comment]
BUILD SUCCESSFUL！Thanks！
1. But what the java result:1 mean?
2. And how can I see the signature and the signature after redact?Use comments like ant -s and ant-r?
3. If I want to change the input, whether I modify ?Main.java(hello,good,dog,cat...)?

**Comment by liusiyu1** [comment]
BUILD SUCCESSFUL！Thanks！
